spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    url: jdbc:mysql://sl-db-011:3306/ZCOMSY?characterEncoding=utf8
    username: red_database
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000 # 30000ms(30) 동안 사용안한 connection 풀에서 제거 - 컴투스기준5초(wait_timeout)

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update

    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  cache:
    type: redis

  redis:
    host: sl-redis-01
    port: 6379




server:
  port: 9080

logging:
  level:
    root: INFO
    web: INFO
    sql: INFO
    was: DEBUG

sentry:
  dsn: https://3f0d7a32b63c4c0f8e12df4baecc4edf@o921467.ingest.sentry.io/5867907
  #exception-resolver-order: 2147483647
  environment: dev
  logging:
    enabled: true
    minimum-event-level: warn
    minimum-breadcrumb-level: warn



#CUSTOM

fluentd:
  defaults:
    host: localhost
    port: 24224
    tag: spring.fluentd
  dw:
    host: localhost
    port: 24224
    tag: was.dw

# LOGBACK CONFIG
logback:
  config.charset: UTF-8
  console.pattern: "%clr(%5p) %clr(%d{yy-MM-dd HH:mm:ss}){magenta}[%thread] [%clr(%logger{0}){cyan}:%line] - %msg%n"
  file:
    path: /home/comsy/log/dev/
    name: file.log
    pattern: "%clr(%5p) %clr(%d{yy-MM-dd HH:mm:ss}){magenta}[%thread] [%clr(%logger{35}){cyan}:%line] - %msg%n"
    rolling_policy:
      file_name_pattern: "file.%d{yyyy-MM-dd}-%i.gz"
      max_file_size: 100MB
      max_history: 30
  access:
    path: /home/comsy/log/dev/
    name: access.log
    pattern: "%msg%n"
    rolling_policy:
      file_name_pattern: "access.%d{yyyy-MM-dd}-%i.gz"
      max_file_size: 100MB
      max_history: 30